services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile  # Ensure the file exists at this location
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
    expose:
      - "3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - my_network
    env_file: .env
    expose:
      - "9000"
    restart: on-failure

#volumes management section
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/lnicoter/data/wordpress'
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/lnicoter/data/mariadb'
      o: 'bind'
networks:
  my_network:
    driver: bridge
