services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile  # Ensure the file exists at this location
    # ports:
    #   - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
    expose:
      - "3306"
    restart: unless-stopped

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/tools:/etc/nginx/tools
      - ./requirements/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    # ports:
    #   - "9000:9000"
    # volumes:
    #   - ./requirements/wordpress:/var/www/wprdpress
    depends_on:
      - mariadb
    networks:
      - my_network
    env_file: .env
    expose:
      - "9000"
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/Users/login/data/wordpress'
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/mariadb'
networks:
  my_network:
    driver: bridge
