services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile  # Ensure the file exists at this location
    # ports:
    #   - "3306:3306"
    env_file: .env
    volumes:
      #per essere chiari con la sintassi dei volumi
      # - <volume_name>:<container_path>
      # the name of the volume is saved for future use on the host
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
    expose:
      - "3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    # volumes:
    #   - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #   - ./requirements/nginx/tools:/etc/nginx/tools
    #   - ./requirements/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    # ports:
    #   - "9000:9000"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - my_network
    env_file: .env
    expose:
      - "9000"
    restart: on-failure

#volumes management section
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: './requirements/wordpress/wordpress_data'
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: './requirements/mariadb/mariadb_data'
      o: 'bind'
networks:
  my_network:
    driver: bridge
